const unitNotesData = {
    'unit1': [
        { frontEmoji: '👀', frontTitle: 'Memerhati', frontQuestion: 'Cuba tengok sekeliling awak! Kita guna deria apa untuk kenal pasti benda?', backEmoji: '🖐️', backTitle: 'Guna 5 Deria', backAnswer: 'Mata untuk melihat, telinga mendengar, hidung menghidu, lidah merasa, dan kulit menyentuh.', trivia: 'Pemerhatian ialah langkah pertama bagi setiap saintis yang hebat! 🌸' },
        { frontEmoji: '🗂️', frontTitle: 'Mengelas', frontQuestion: 'Kucing dan harimau dalam kumpulan yang sama. Kenapa ya?', backEmoji: '🐅', backTitle: 'Ciri yang Sama', backAnswer: 'Mengelas bermaksud mengasingkan benda ikut sifatnya. Contoh: Asingkan haiwan berkaki empat!', trivia: 'Cuba kelaskan rakan di kelas awak. Ada yang pakai cermin mata, ada yang tidak! 👓' },
        { frontEmoji: '📏', frontTitle: 'Mengukur dan Menggunakan Nombor', frontQuestion: 'Macam mana nak tahu berapa panjang meja ini dengan tepat?', backEmoji: '📐', backTitle: 'Guna Alat Betul', backAnswer: 'Kita guna pembaris atau pita pengukur. Tak boleh sekadar teka-teka!', trivia: 'Zaman dulu, orang ukur guna jengkal tangan. Tapi tangan orang tak sama besar, jadi selalu salah! 🤭' },
        { frontEmoji: '🗣️', frontTitle: 'Berkomunikasi', frontQuestion: 'Selain bercakap, macam mana saintis kongsi rekod?', backEmoji: '📝', backTitle: 'Lakaran & Carta', backAnswer: 'Saintis tak semestinya bercakap. Mereka lukis lakaran, buat jadual, dan carta supaya mudah faham!', trivia: 'Awak pun sedang berkomunikasi bila lukis gambar pokok untuk kawan! 🎨' },
        { frontEmoji: '🔬', frontTitle: 'Kemahiran Manipulatif', frontQuestion: 'Bila guna bikar kaca, kita kena pegang macam mana?', backEmoji: '🧤', backTitle: 'Pegang dengan Cermat', backAnswer: 'Gunakan alatan dengan betul, lakar spesimen, bersihkan alat, dan simpan dengan selamat.', trivia: 'Kalau cuai, bikar boleh pecah dan tangan awak terluka! 🩸' }
    ],
    'unit2': [
        { frontEmoji: '🛑', frontTitle: 'Patuhi dan Fahami Peraturan Bilik Sains', frontQuestion: 'Apakah peraturan paling penting bila masuk Bilik Sains?', backEmoji: '🤫', backTitle: 'Keselamatan Utama', backAnswer: 'Beratur sebelum masuk, dilarang makan/minum, lapor kecederaan, dan buang sisa di tempat betul.', trivia: 'Peraturan ini wujud supaya tiada siapa cedera terkena bahan kimia! 🧪' }
    ],
    'unit3': [
        { frontEmoji: '👶', frontTitle: 'Manusia Membiak', frontQuestion: 'Macam mana jumlah manusia makin bertambah di Bumi?', backEmoji: '🤰', backTitle: 'Melahirkan Anak', backAnswer: 'Manusia adalah kumpulan hidupan yang membiak dengan cara melahirkan anak.', trivia: 'Haiwan seperti kucing dan lembu pun membiak dengan cara yang sama! 🐄' },
        { frontEmoji: '📏', frontTitle: 'Saya Membesar', frontQuestion: 'Apa bukti yang menunjukkan awak semakin membesar?', backEmoji: '👕', backTitle: 'Saiz Bertambah', backAnswer: 'Bila kita membesar, saiz badan, berat, dan tinggi kita akan bertambah!', trivia: 'Cuba pakai baju masa umur awak 2 tahun. Mesti dah ketat kan? 😂' },
        { frontEmoji: '🏃‍♂️', frontTitle: 'Tumbesaran Berbeza', frontQuestion: 'Awak dengan kawan awak umur sama, tapi kenapa tinggi berbeza?', backEmoji: '⚖️', backTitle: 'Setiap Orang Unik', backAnswer: 'Kadar tumbesaran manusia berbeza-beza. Ada kawan yang tinggi, ada yang rendah sedikit. Itu normal!', trivia: 'Makanan berkhasiat macam susu boleh bantu awak membesar dengan sihat! 🥛' },
        { frontEmoji: '🧬', frontTitle: 'Pewarisan', frontQuestion: 'Kenapa warna rambut atau muka awak iras-iras mak ayah awak?', backEmoji: '👨‍👦', backTitle: 'Diwarisi', backAnswer: 'Sebab ciri-ciri seperti jenis rambut, warna kulit dan warna mata "diwarisi" dari keturunan kita.', trivia: 'Pewarisan ini menjadikan setiap keluarga nampak serupa tapi tak sama! ✨' }
    ],
    'unit4': [
        { frontEmoji: '🥚', frontTitle: 'Haiwan Membiak', frontQuestion: 'Ayam dan lembu, dua-dua ada anak. Macam mana caranya?', backEmoji: '🐄', backTitle: 'Bertelur vs Beranak', backAnswer: 'Haiwan membiak dengan dua cara: Ada yang bertelur (ayam), ada yang melahirkan anak (lembu).', trivia: 'Paus adalah haiwan lautan tapi ia BUKAN bertelur, ia melahirkan anak! 🐳' },
        { frontEmoji: '🐢', frontTitle: 'Bertelur Sedikit, Bertelur Banyak', frontQuestion: 'Adakah semua haiwan bertelur banyak sekaligus?', backEmoji: '🦆', backTitle: 'Tak Sama!', backAnswer: 'Penyu dan katak bertelur sangat banyak (beratus biji)! Tapi burung penguin hanya bertelur sedikit.', trivia: 'Katak bertelur ratusan biji telur sebab kebarangkalian telurnya dimakan musuh sangat tinggi. 😱' },
        { frontEmoji: '🐈', frontTitle: 'Beranak Sedikit, Beranak Banyak', frontQuestion: 'Kucing dan ikan lumba-lumba melahirkan anak. Siapa beranak lebih banyak?', backEmoji: '🐬', backTitle: 'Kucing!', backAnswer: 'Kucing dan arnab beranak banyak (beberapa ekor sekaligus). Paus dan lembu beranak sedikit (biasanya seekor).', trivia: 'Arnab boleh lahirkan sehingga 14 ekor anak dalam satu masa! 🐇' },
        { frontEmoji: '🐸', frontTitle: 'Kami Serupa, Kami Berbeza', frontQuestion: 'Semua anak haiwan rupa sama macam ibunya kah bila lahir?', backEmoji: '🦋', backTitle: 'Kami Berbeza!', backAnswer: 'Anak lembu serupa ibunya. Tapi anak rama-rama (beluncas) atau katak (berudu) lansung TAK SAMA macam ibunya!', trivia: 'Berudu bernafas guna insang dalam air sebelum jadi katak yang bernafas guna paru-paru! 💧' },
        { frontEmoji: '🔄', frontTitle: 'Kitar Hidup Haiwan', frontQuestion: 'Apakah turutan kitar hidup seekor rama-rama?', backEmoji: '🐛', backTitle: '4 Peringkat', backAnswer: 'Telur ➔ Beluncas (Larva) ➔ Kepompong (Pupa) ➔ Rama-rama dewasa!', trivia: 'Proses pertukaran bentuk yang sangat menakjubkan ini dipanggil "Metamorfosis". 🌟' }
    ],
    'unit5': [
        { frontEmoji: '🌿', frontTitle: 'Kepentingan Tumbuh-tumbuhan', frontQuestion: 'Kenapa tumbuh-tumbuhan sangat penting pada manusia & haiwan?', backEmoji: '🏡', backTitle: 'Sumber Utama', backAnswer: 'Pokok beri kita habitat (tempat tinggal), udara (oksigen), makanan, dan ubat-ubatan.', trivia: 'Buku nota dan pensel awak pun asalnya diperbuat daripada kayu pokok! 📝' },
        { frontEmoji: '🌰', frontTitle: 'Keperluan Asas Biji Benih Bercambah', frontQuestion: 'Biji benih perlu apa untuk mula pecah dan keluar akar?', backEmoji: '💧', backTitle: 'Air, Udara, Suhu', backAnswer: 'Biji benih HANYA perlukan Air, Udara dan Suhu yang sesuai untuk bercambah. (Cahaya belum perlu).', trivia: 'Biji benih tak perlukan matahari waktu mula bercambah sebab ia tertimbus dalam tanah gelap! 🌑' },
        { frontEmoji: '🌱', frontTitle: 'Tumbesaranku', frontQuestion: 'Apa yang berubah bila anak pokok makin membesar?', backEmoji: '🌳', backTitle: 'Makin Tinggi', backAnswer: 'Bilangan daun makin banyak, saiz daun makin besar, lilitan batang makin lebar, dan pokok makin tinggi.', trivia: 'Ada pokok balak yang lilitan batangnya sangat besar sampaikan 10 orang pegang tangan tak cukup! 🌲' },
        { frontEmoji: '🔄', frontTitle: 'Urutan Tumbesaran Tumbuh-tumbuhan', frontQuestion: 'Sebutkan langkah-langkah pokok tomato membesar.', backEmoji: '🍅', backTitle: 'Dari Benih ke Buah', backAnswer: 'Biji Benih ➔ Biji Benih Bercambah ➔ Anak Pokok ➔ Pokok Berbunga ➔ Pokok Berbuah!', trivia: 'Bunga pokok sebenarnya bertukar menjadi buah selepas proses pendebungaan! 🐝' },
        { frontEmoji: '☀️', frontTitle: 'Keperluan Asas Tumbesaran', frontQuestion: 'Bila dah jadi pokok, apa dia perlukan untuk hidup sihat?', backEmoji: '💦', backTitle: 'Air, Cahaya & Udara', backAnswer: 'Pokok WAJIB perlukan Cahaya Matahari, Air, dan Udara untuk membuat makanannya sendiri.', trivia: 'Baja adalah nutrien tambahan supaya dia tumbuh lebih gemuk dan subur! 🥗' }
    ],
    'unit6': [
        { frontEmoji: '🌞', frontTitle: 'Sumber Cahaya', frontQuestion: 'Dari manakah datangnya cahaya di Bumi ini?', backEmoji: '😎', backTitle: 'Matahari!', backAnswer: 'Matahari ialah sumber cahaya utama semula jadi. Selain itu kita ada lampu dan api.', trivia: 'Matahari sebenarnya adalah sebiji bintang gergasi yang sangat panas! ⭐' },
        { frontEmoji: '💡', frontTitle: 'Terang dan Gelap', frontQuestion: 'Apa beza aktiviti waktu terang dan waktu gelap?', backEmoji: '🔍', backTitle: 'Senang Melihat', backAnswer: 'Waktu terang (ada cahaya) memudahkan kita melihat. Waktu gelap menyukarkan pemerhatian.', trivia: 'Kucing ada mata istimewa yang boleh melihat dalam gelap lebih baik dari manusia! 🐈' },
        { frontEmoji: '👤', frontTitle: 'Bayang-bayang', frontQuestion: 'Macam mana bayang-bayang hitam tu boleh terhasil?', backEmoji: '🌑', backTitle: 'Cahaya Dihalang', backAnswer: 'Bayang-bayang terbentuk apabila pergerakan cahaya lurus DIHALANG oleh suatu objek.', trivia: 'Bila awak halang jalan cahaya, kawasan di belakang awak yang tak kena cahaya tulah bayang! 🕵️' },
        { frontEmoji: '🔍', frontTitle: 'Kejelasan Bayang-bayang', frontQuestion: 'Sama hitam ke bayang-bayang plastik jernih berbanding buku tebal?', backEmoji: '🔲', backTitle: 'Legap vs Lut Sinar', backAnswer: 'Tak sama! Objek legap (buku) hasilkan bayang jelas. Objek lut sinar (plastik jernih) tiada bayang!', trivia: 'Kaca tingkap rumah adalah lut sinar supaya cahaya penuh boleh masuk. 🪟' },
        { frontEmoji: '🎭', frontTitle: 'Permainan Bayang-bayang', frontQuestion: 'Boleh tak bayang-bayang bertukar saiz dan bentuk?', backEmoji: '🦅', backTitle: 'Boleh!', backAnswer: 'Saiz bayang berubah bergantung jarak lampu dengan objek. Bentuk pula ikut kedudukan objek.', trivia: 'Makin dekat objek dengan lampu, makin BESAR bayangnya! 📏' },
        { frontEmoji: '✂️', frontTitle: 'Mencipta Permainan Wayang Kertas', frontQuestion: 'Pernah tengok wayang kulit?', backEmoji: '🔦', backTitle: 'Guna Cahaya', backAnswer: 'Kita boleh cipta patung kertas sendiri. Suluh lampu dari depan, dan bayangnya akan jatuh ke skrin layar!', trivia: 'Wayang Kulit adalah permainan tradisional Melayu yang guna konsep bayang-bayang! 🪕' }
    ],
    'unit7': [
        { frontEmoji: '🔌', frontTitle: 'Kenali Komponen Elektrik', frontQuestion: 'Apa 3 komponen asas dalam litar elektrik?', backEmoji: '🔋', backTitle: 'Bateri, Suis, Mentol', backAnswer: 'Litar asas menggunakan Sel Kering (bateri), Suis, dan Mentol, disambung dengan wayar.', trivia: 'Bateri bersaiz AA yang kita selalu guna tu ialah contoh "Sel Kering". ⚡' },
        { frontEmoji: '⚙️', frontTitle: 'Fungsi Komponen Elektrik', frontQuestion: 'Apa tugas suis dalam litar elektrik?', backEmoji: '✂️', backTitle: 'Menyambung Arus', backAnswer: 'Suis menyambung atau memutuskan arus. Mentol hasilkan cahaya. Sel Kering beri tenaga elektrik.', trivia: 'Tanpa sel kering, litar lengkap sekalipun takkan boleh menyalakan mentol. 🔋' },
        { frontEmoji: '💡', frontTitle: 'Membina Litar Elektrik', frontQuestion: 'Bila mentol akan menyala?', backEmoji: '🌟', backTitle: 'Litar Lengkap', backAnswer: 'Mentol hanya akan menyala jika litar disambung lengkap dan suis DITUTUP (ON).', trivia: 'Perkataan "Tutup Suis" dalam sains bermaksud menyambungkan litar. Jangan keliru ya! 🔄' },
        { frontEmoji: '⚠️', frontTitle: 'Mengapakah Mentol Tidak Menyala?', frontQuestion: 'Saya dah pasang wayar, kenapa mentol masih tak nyala?', backEmoji: '❌', backTitle: 'Litar Tak Lengkap', backAnswer: 'Mungkin suis masih TERBUKA, sel kering habis tenaga, mentol rosak, atau pemasangan wayar salah.', trivia: 'Litar terbuka ibarat jambatan putus, arus elektrik tak boleh melintas! 🌉' },
        { frontEmoji: '🪙', frontTitle: 'Konduktor dan Penebat', frontQuestion: 'Boleh ke wayar diganti dengan pemadam getah atau paku besi?', backEmoji: '🛡️', backTitle: 'Konduktor vs Penebat', backAnswer: 'Paku besi ialah KONDUKTOR (mengalirkan arus, mentol nyala). Pemadam ialah PENEBAT (menghalang arus, mentol padam).', trivia: 'Plastik membalut wayar elektrik di rumah awak ialah Penebat supaya awak tak terkena renjatan! ⚡🚫' }
    ],
    'unit8': [
        { frontEmoji: '🧹', frontTitle: 'Kaedah Mengasingkan Campuran', frontQuestion: 'Klip kertas besi bercampur dalam tepung. Macam mana nak asingkan?', backEmoji: '🧲', backTitle: 'Guna Magnet', backAnswer: 'Kita guna magnet. Kaedah lain: Menyisih, Mengayak, Menuras (guna penapis), dan Mengapung.', trivia: 'Mengayak sangat bagus untuk asingkan pasir kasar daripada gula halus! 🕳️' },
        { frontEmoji: '🧂', frontTitle: 'Bahan Larut dan Bahan Tidak Larut', frontQuestion: 'Kalau letak garam dalam air teh, lama-lama hilang. Kenapa?', backEmoji: '☕', backTitle: 'Bahan Larut', backAnswer: 'Garam dan gula "larut" dalam air. Bahan macam batu dan pasir pula TIDAK LARUT walau kuat mana pun dikacau.', trivia: 'Air laut rasa masin kerana ada sangat banyak garam yang terlarut di dalamnya! 🌊' },
        { frontEmoji: '🥄', frontTitle: 'Bahan Larut Lebih Cepat', frontQuestion: 'Milo lambat nak hancur! Apa rahsia nak bagi bahan cepat larut?', backEmoji: '🌪️', backTitle: 'Air Panas & Kacau Laju', backAnswer: 'Bahan lebih cepat larut jika kita menggunakan AIR PANAS, mengacau dengan laju, atau guna saiz bahan yang kecil.', trivia: 'Gula pasir lebih cepat larut berbanding ketulan gula batu yang besar! 🧊' }
    ],
    'unit9': [
        { frontEmoji: '🌧️', frontTitle: 'Sumber Air Semula Jadi', frontQuestion: 'Air yang kita minum hari-hari, asalnya dari mana?', backEmoji: '🌊', backTitle: 'Hujan, Sungai, Laut', backAnswer: 'Sumber air semula jadi kita ialah hujan, sungai, tasik, laut, dan mata air.', trivia: 'Walaupun laut sangat besar, airnya masin dan tak boleh diminum terus! 🧂' },
        { frontEmoji: '🏞️', frontTitle: 'Air Mengalir', frontQuestion: 'Adakah air di sungai duduk diam sahaja?', backEmoji: '🌊', backTitle: 'Air Bergerak', backAnswer: 'Tidak. Air sentiasa mengalir dari kawasan tinggi (gunung) menuju ke kawasan yang lebih rendah (laut).', trivia: 'Kawasan air mengalir yang jatuh dari tebing tinggi dipanggil Air Terjun! ⛰️' },
        { frontEmoji: '🗺️', frontTitle: 'Aliran Air Semula Jadi', frontQuestion: 'Ke manakah air sungai mengalir akhirnya?', backEmoji: '🌊', backTitle: 'Menuju Laut', backAnswer: 'Air mengalir dari mata air di gunung, masuk ke sungai, dan akhirnya akan bermuara (berhenti) di lautan luas.', trivia: 'Perjalanan air ini sangat panjang dan menyokong kehidupan banyak haiwan darat! 🐘' },
        { frontEmoji: '🔄', frontTitle: 'Kitaran Air Semula Jadi', frontQuestion: 'Macam mana hujan boleh terjadi?', backEmoji: '☁️', backTitle: 'Wap Air Naik', backAnswer: 'Air sungai/laut menyejat jadi wap ➔ Naik ke langit jadi Awan ➔ Awan berat dan turunkan Hujan ➔ Balik ke sungai!', trivia: 'Kitaran air memastikan bekalan air di Bumi tak pernah habis! 🌍' },
        { frontEmoji: '💨', frontTitle: 'Udara', frontQuestion: 'Kita tak boleh nampak udara. Di mana ia wujud?', backEmoji: '🍃', backTitle: 'Di Sekeliling Kita', backAnswer: 'Udara ada di mana-mana sahaja, termasuk dalam air dan tanah! Udara mengandungi pelbagai gas seperti oksigen.', trivia: 'Ikan di dalam laut pun bernafas menggunakan udara (oksigen) yang terlarut dalam air! 🐟' },
        { frontEmoji: '🪁', frontTitle: 'Udara Bergerak', frontQuestion: 'Apa itu angin?', backEmoji: '🌪️', backTitle: 'Angin!', backAnswer: 'Udara yang bergerak dipanggil ANGIN. Angin membantu menerbangkan layang-layang dan mengeringkan baju.', trivia: 'Angin yang terlalu kuat dipanggil ribut dan boleh menumbangkan pokok! 🌲' },
        { frontEmoji: '🚀', frontTitle: 'Mencipta Roket Angin', frontQuestion: 'Boleh ke kita cipta mainan bergerak guna udara?', backEmoji: '🎈', backTitle: 'Boleh!', backAnswer: 'Kita boleh hasilkan roket kertas menggunakan belon. Udara yang keluar menolak belon meluncur laju ke depan.', trivia: 'Daya tolakan udara inilah yang digunakan oleh roket angkasa lepas sebenar! ✨' }
    ],
    'unit10': [
        { frontEmoji: '⚙️', frontTitle: 'Binaan Pilihan Saya', frontQuestion: 'Apa itu Set Binaan?', backEmoji: '🏰', backTitle: 'Cantum Komponen', backAnswer: 'Set binaan (seperti Lego) mempunyai komponen berbeza bentuk untuk dicantumkan menjadi pelbagai model menarik.', trivia: 'Membina model melatih otak awak supaya lebih kreatif dan bijak menyelesaikan masalah! 🧠' },
        { frontEmoji: '📖', frontTitle: 'Mengenali Komponen dalam Manual Bergambar', frontQuestion: 'Kenapa bila beli mainan baru, ada satu buku kecil disertakan?', backEmoji: '📋', backTitle: 'Buku Manual', backAnswer: 'Manual menerangkan jenis komponen dan langkah-langkah memasang model secara teratur dan betul.', trivia: 'Jurutera sebenar pun merujuk "manual" atau pelan lantai sebelum membina rumah! 🏗️' },
        { frontEmoji: '👷', frontTitle: 'Jurutera Cilik', frontQuestion: 'Bagaimana cara nak pasang model robot tanpa salah langkah?', backEmoji: '🔍', backTitle: 'Ikut Urutan', backAnswer: 'Awak mesti kenal pasti komponen dan ikut arahan bergambar dalam buku manual langkah demi langkah.', trivia: 'Kalau terlangkau satu langkah, robot awak mungkin tak boleh berdiri seimbang! 🤖' },
        { frontEmoji: '🎨', frontTitle: 'Saya Kreatif', frontQuestion: 'Mesti ke sentiasa ikut manual?', backEmoji: '🚀', backTitle: 'Tak Semestinya!', backAnswer: 'Lepas mahir, awak bebas berimaginasi! Awak boleh reka bentuk model unik sendiri seperti kereta terbang.', trivia: 'Perekacipta tersohor dunia bermula dengan selalu bermain mencantum barang baharu. 🌟' },
        { frontEmoji: '📦', frontTitle: 'Buka dan Simpan', frontQuestion: 'Dah siap main bina model, apa tanggungjawab kita?', backEmoji: '🧹', backTitle: 'Kemas Semula', backAnswer: 'Buka semula binaan mengikut urutan terbalik, asingkan ikut saiz/bentuk, dan simpan dalam bekas dengan kemas.', trivia: 'Kalau bersepah di lantai, komponen boleh hilang dan memijaknya akan sangat menyakitkan kaki! 😖' }
    ]
};
