window.SAINS_AUDIO_DB = {
"4 Peringkat": "audio/8cb47c9c03f7.mp3",
"Ada pokok balak yang lilitan batangnya sangat besar sampaikan 10 orang pegang tangan tak cukup!": "audio/a3f459a1ca9b.mp3",
"Adakah air di sungai duduk diam sahaja?": "audio/e71e9d286ade.mp3",
"Adakah semua haiwan bertelur banyak sekaligus?": "audio/7c598386f80a.mp3",
"Air Bergerak": "audio/fc2454b95f25.mp3",
"Air Mengalir": "audio/e5b0842a3ec7.mp3",
"Air Mengalir: Air Bergerak": "audio/0ea0291fa140.mp3",
"Air Panas & Kacau Laju": "audio/d5c9c8c01050.mp3",
"Air laut rasa masin kerana ada sangat banyak garam yang terlarut di dalamnya!": "audio/d51ed55a20fc.mp3",
"Air mengalir dari mata air di gunung, masuk ke sungai, dan akhirnya akan bermuara (berhenti) di lautan luas.": "audio/cb77d3ab3bcb.mp3",
"Air mengalir dari mata air di gunung, masuk ke sungai, dan akhirnya akan bermuara (berhenti) di lautan luas.  Perjalanan air ini sangat panjang dan menyokong kehidupan banyak haiwan darat!": "audio/6055dd830f3e.mp3",
"Air sungai/laut menyejat jadi wap  Naik ke langit jadi Awan  Awan berat dan turunkan Hujan  Balik ke sungai!": "audio/775ee3111a87.mp3",
"Air sungai/laut menyejat jadi wap  Naik ke langit jadi Awan  Awan berat dan turunkan Hujan  Balik ke sungai!  Kitaran air memastikan bekalan air di Bumi tak pernah habis!": "audio/4bf4aabe5e7d.mp3",
"Air yang kita minum hari-hari, asalnya dari mana?": "audio/0206d54b5bea.mp3",
"Air, Cahaya & Udara": "audio/06845cce65cd.mp3",
"Air, Udara, Suhu": "audio/ff58a4e7ac8b.mp3",
"Aliran Air Semula Jadi": "audio/bb165b38d41c.mp3",
"Aliran Air Semula Jadi: Menuju Laut": "audio/5911254a4b79.mp3",
"Anak lembu serupa ibunya. Tapi anak rama-rama (beluncas) atau katak (berudu) lansung TAK SAMA macam ibunya!": "audio/bd79988d2581.mp3",
"Anak lembu serupa ibunya. Tapi anak rama-rama (beluncas) atau katak (berudu) lansung TAK SAMA macam ibunya!  Berudu bernafas guna insang dalam air sebelum jadi katak yang bernafas guna paru-paru!": "audio/c624aca21aec.mp3",
"Angin yang terlalu kuat dipanggil ribut dan boleh menumbangkan pokok!": "audio/10058d33d34c.mp3",
"Angin!": "audio/f85392c29c8d.mp3",
"Apa 3 komponen asas dalam litar elektrik?": "audio/3c1e996d6f6f.mp3",
"Apa beza aktiviti waktu terang dan waktu gelap?": "audio/39beaaaf78c6.mp3",
"Apa bukti yang menunjukkan awak semakin membesar?": "audio/21c5440c0cf1.mp3",
"Apa itu Set Binaan?": "audio/60b87cc76361.mp3",
"Apa itu angin?": "audio/9110acf9994e.mp3",
"Apa tugas suis dalam litar elektrik?": "audio/b9ab68231702.mp3",
"Apa yang berubah bila anak pokok makin membesar?": "audio/172916eecfd8.mp3",
"Apakah peraturan paling penting bila masuk Bilik Sains?": "audio/7eb22505bb10.mp3",
"Apakah turutan kitar hidup seekor rama-rama?": "audio/e87ead0a7f76.mp3",
"Arnab boleh lahirkan sehingga 14 ekor anak dalam satu masa!": "audio/9a96e7a71290.mp3",
"Awak dengan kawan awak umur sama, tapi kenapa tinggi berbeza?": "audio/59c15149f76b.mp3",
"Awak mesti kenal pasti komponen dan ikut arahan bergambar dalam buku manual langkah demi langkah.": "audio/c4596cbd4953.mp3",
"Awak mesti kenal pasti komponen dan ikut arahan bergambar dalam buku manual langkah demi langkah.  Kalau terlangkau satu langkah, robot awak mungkin tak boleh berdiri seimbang!": "audio/c7886ebe519d.mp3",
"Awak pun sedang berkomunikasi bila lukis gambar pokok untuk kawan!": "audio/f1259d418e2c.mp3",
"Ayam dan lembu, dua-dua ada anak. Macam mana caranya?": "audio/a6b81a642714.mp3",
"Bagaimana cara nak pasang model robot tanpa salah langkah?": "audio/d03a00e55e6e.mp3",
"Bahan Larut": "audio/ed561aae0562.mp3",
"Bahan Larut Lebih Cepat": "audio/df61aa66856e.mp3",
"Bahan Larut Lebih Cepat: Air Panas & Kacau Laju": "audio/61490b7697ad.mp3",
"Bahan Larut dan Bahan Tidak Larut": "audio/b8550ba9f231.mp3",
"Bahan Larut dan Bahan Tidak Larut: Bahan Larut": "audio/ff18f4a8e4d4.mp3",
"Bahan lebih cepat larut jika kita menggunakan AIR PANAS, mengacau dengan laju, atau guna saiz bahan yang kecil.": "audio/371e870dc973.mp3",
"Bahan lebih cepat larut jika kita menggunakan AIR PANAS, mengacau dengan laju, atau guna saiz bahan yang kecil.  Gula pasir lebih cepat larut berbanding ketulan gula batu yang besar!": "audio/d14a89393bde.mp3",
"Baja adalah nutrien tambahan supaya dia tumbuh lebih gemuk dan subur!": "audio/08704cb307dd.mp3",
"Bateri bersaiz AA yang kita selalu guna tu ialah contoh \"Sel Kering\".": "audio/a314e1e4d114.mp3",
"Bateri, Suis, Mentol": "audio/a663ae1dc47f.mp3",
"Bayang-bayang": "audio/0e25226965c0.mp3",
"Bayang-bayang terbentuk apabila pergerakan cahaya lurus DIHALANG oleh suatu objek.": "audio/b5d4328e524e.mp3",
"Bayang-bayang terbentuk apabila pergerakan cahaya lurus DIHALANG oleh suatu objek.  Bila awak halang jalan cahaya, kawasan di belakang awak yang tak kena cahaya tulah bayang! ️": "audio/75642178d4fd.mp3",
"Bayang-bayang: Cahaya Dihalang": "audio/e0bf42b054ca.mp3",
"Beranak Sedikit, Beranak Banyak": "audio/86c30b15d078.mp3",
"Beranak Sedikit, Beranak Banyak: Kucing!": "audio/d6486a443a6f.mp3",
"Beratur sebelum masuk, dilarang makan/minum, lapor kecederaan, dan buang sisa di tempat betul.": "audio/0a99ab0854ed.mp3",
"Beratur sebelum masuk, dilarang makan/minum, lapor kecederaan, dan buang sisa di tempat betul.  Peraturan ini wujud supaya tiada siapa cedera terkena bahan kimia!": "audio/79642c79ba3c.mp3",
"Berkomunikasi": "audio/8fb0b18486a8.mp3",
"Berkomunikasi: Lakaran & Carta": "audio/5f88565f2341.mp3",
"Bertelur Sedikit, Bertelur Banyak": "audio/81b9651d46b3.mp3",
"Bertelur Sedikit, Bertelur Banyak: Tak Sama!": "audio/ca2af214b6fb.mp3",
"Bertelur vs Beranak": "audio/39bcca89e0af.mp3",
"Berudu bernafas guna insang dalam air sebelum jadi katak yang bernafas guna paru-paru!": "audio/dec463168b41.mp3",
"Betul": "audio/13508a7fa41d.mp3",
"Betul atau salah?": "audio/bf30705f7a5b.mp3",
"Betul! Kamu memang bijak!": "audio/b8aca187cc92.mp3",
"Biji Benih  Biji Benih Bercambah  Anak Pokok  Pokok Berbunga  Pokok Berbuah!": "audio/74860e3b51af.mp3",
"Biji Benih  Biji Benih Bercambah  Anak Pokok  Pokok Berbunga  Pokok Berbuah!  Bunga pokok sebenarnya bertukar menjadi buah selepas proses pendebungaan!": "audio/d06b1455da31.mp3",
"Biji benih HANYA perlukan Air, Udara dan Suhu yang sesuai untuk bercambah. (Cahaya belum perlu).": "audio/d6d8d8ad255b.mp3",
"Biji benih HANYA perlukan Air, Udara dan Suhu yang sesuai untuk bercambah. (Cahaya belum perlu).  Biji benih tak perlukan matahari waktu mula bercambah sebab ia tertimbus dalam tanah gelap!": "audio/3e4c94d8bcaa.mp3",
"Biji benih perlu apa untuk mula pecah dan keluar akar?": "audio/1091c4596443.mp3",
"Biji benih tak perlukan matahari waktu mula bercambah sebab ia tertimbus dalam tanah gelap!": "audio/0a0c5a421714.mp3",
"Bila awak halang jalan cahaya, kawasan di belakang awak yang tak kena cahaya tulah bayang! ️": "audio/702d00cc16ee.mp3",
"Bila dah jadi pokok, apa dia perlukan untuk hidup sihat?": "audio/916feabbcba1.mp3",
"Bila guna bikar kaca, kita kena pegang macam mana?": "audio/04e192f8c2d5.mp3",
"Bila kita membesar, saiz badan, berat, dan tinggi kita akan bertambah!": "audio/51ccb99a5c1d.mp3",
"Bila kita membesar, saiz badan, berat, dan tinggi kita akan bertambah!  Cuba pakai baju masa umur awak 2 tahun. Mesti dah ketat kan?": "audio/4cfbab984de2.mp3",
"Bila mentol akan menyala?": "audio/f96f2e2dacb3.mp3",
"Bilangan daun makin banyak, saiz daun makin besar, lilitan batang makin lebar, dan pokok makin tinggi.": "audio/0015ce3b5287.mp3",
"Bilangan daun makin banyak, saiz daun makin besar, lilitan batang makin lebar, dan pokok makin tinggi.  Ada pokok balak yang lilitan batangnya sangat besar sampaikan 10 orang pegang tangan tak cukup!": "audio/24506e080737.mp3",
"Binaan Pilihan Saya": "audio/43112ab3bfbd.mp3",
"Binaan Pilihan Saya: Cantum Komponen": "audio/f57fd22bc249.mp3",
"Boleh ke kita cipta mainan bergerak guna udara?": "audio/b3186aad1d1f.mp3",
"Boleh ke wayar diganti dengan pemadam getah atau paku besi?": "audio/a3191c6891be.mp3",
"Boleh tak bayang-bayang bertukar saiz dan bentuk?": "audio/a543bc518641.mp3",
"Boleh!": "audio/c8bf6db13556.mp3",
"Buka dan Simpan": "audio/c0d7cee96914.mp3",
"Buka dan Simpan: Kemas Semula": "audio/2e4ac85f6551.mp3",
"Buka semula binaan mengikut urutan terbalik, asingkan ikut saiz/bentuk, dan simpan dalam bekas dengan kemas.": "audio/1c45a404aab5.mp3",
"Buka semula binaan mengikut urutan terbalik, asingkan ikut saiz/bentuk, dan simpan dalam bekas dengan kemas.  Kalau bersepah di lantai, komponen boleh hilang dan memijaknya akan sangat menyakitkan kaki!": "audio/957b3125e6a3.mp3",
"Buku Manual": "audio/48d338d1ca1a.mp3",
"Buku nota dan pensel awak pun asalnya diperbuat daripada kayu pokok!": "audio/a6c9d9007a25.mp3",
"Bunga pokok sebenarnya bertukar menjadi buah selepas proses pendebungaan!": "audio/cad10577d3ae.mp3",
"Cahaya Dihalang": "audio/413c3fb68aa5.mp3",
"Cantum Komponen": "audio/32387bf7d8af.mp3",
"Ciri yang Sama": "audio/258171e2ef3c.mp3",
"Cuba kelaskan rakan di kelas awak. Ada yang pakai cermin mata, ada yang tidak!": "audio/1e85f3de17f5.mp3",
"Cuba pakai baju masa umur awak 2 tahun. Mesti dah ketat kan?": "audio/5abf26c16b4e.mp3",
"Cuba tengok sekeliling awak! Kita guna deria apa untuk kenal pasti benda?": "audio/d6485d2d6a6d.mp3",
"Dah siap main bina model, apa tanggungjawab kita?": "audio/5542b9a24502.mp3",
"Dari Benih ke Buah": "audio/d7023866c8ac.mp3",
"Dari manakah datangnya cahaya di Bumi ini?": "audio/5f027207d674.mp3",
"Daya tolakan udara inilah yang digunakan oleh roket angkasa lepas sebenar!": "audio/56a67f7f690f.mp3",
"Di Sekeliling Kita": "audio/9ff8638037de.mp3",
"Diwarisi": "audio/3dc0f3161f30.mp3",
"Fungsi Komponen Elektrik": "audio/2ea89bd6d27c.mp3",
"Fungsi Komponen Elektrik: Menyambung Arus": "audio/66e88b228c5b.mp3",
"Garam dan gula \"larut\" dalam air. Bahan macam batu dan pasir pula TIDAK LARUT walau kuat mana pun dikacau.": "audio/9e4a6566dd33.mp3",
"Garam dan gula \"larut\" dalam air. Bahan macam batu dan pasir pula TIDAK LARUT walau kuat mana pun dikacau.  Air laut rasa masin kerana ada sangat banyak garam yang terlarut di dalamnya!": "audio/8e358b0b1a4c.mp3",
"Gula pasir lebih cepat larut berbanding ketulan gula batu yang besar!": "audio/88ba3d8a3a8c.mp3",
"Guna 5 Deria": "audio/4c5208e87f1a.mp3",
"Guna Alat Betul": "audio/d729af86ddf2.mp3",
"Guna Cahaya": "audio/846c934e6620.mp3",
"Guna Magnet": "audio/7226d9b73095.mp3",
"Gunakan alatan dengan betul, lakar spesimen, bersihkan alat, dan simpan dengan selamat.": "audio/cb5fa0d01338.mp3",
"Gunakan alatan dengan betul, lakar spesimen, bersihkan alat, dan simpan dengan selamat.  Kalau cuai, bikar boleh pecah dan tangan awak terluka!": "audio/7c47d923e719.mp3",
"Hai! Saya Boti. Jom terokai pulau sains!": "audio/d31a5bb31872.mp3",
"Haiwan Membiak": "audio/aa821dfe901a.mp3",
"Haiwan Membiak: Bertelur vs Beranak": "audio/08f8c7a7e7b0.mp3",
"Haiwan membiak dengan dua cara: Ada yang bertelur (ayam), ada yang melahirkan anak (lembu).": "audio/7f25f86e6629.mp3",
"Haiwan membiak dengan dua cara: Ada yang bertelur (ayam), ada yang melahirkan anak (lembu).  Paus adalah haiwan lautan tapi ia BUKAN bertelur, ia melahirkan anak!": "audio/30830231eaba.mp3",
"Haiwan seperti kucing dan lembu pun membiak dengan cara yang sama!": "audio/2d5699e0f920.mp3",
"Hampir betul! Jangan putus asa.": "audio/169987383b02.mp3",
"Hujan, Sungai, Laut": "audio/53c0918b2073.mp3",
"Ikan di dalam laut pun bernafas menggunakan udara (oksigen) yang terlarut dalam air!": "audio/0d69e44be51d.mp3",
"Ikut Urutan": "audio/9d405e2d5929.mp3",
"Jurutera Cilik": "audio/4faf062a078a.mp3",
"Jurutera Cilik: Ikut Urutan": "audio/620bf2718411.mp3",
"Jurutera sebenar pun merujuk \"manual\" atau pelan lantai sebelum membina rumah! ️": "audio/ed59611adcb4.mp3",
"Kaca tingkap rumah adalah lut sinar supaya cahaya penuh boleh masuk.": "audio/796f2f0486d5.mp3",
"Kadar tumbesaran manusia berbeza-beza. Ada kawan yang tinggi, ada yang rendah sedikit. Itu normal!": "audio/66cba56462fd.mp3",
"Kadar tumbesaran manusia berbeza-beza. Ada kawan yang tinggi, ada yang rendah sedikit. Itu normal!  Makanan berkhasiat macam susu boleh bantu awak membesar dengan sihat!": "audio/a2e80a707452.mp3",
"Kaedah Mengasingkan Campuran": "audio/32148e96a663.mp3",
"Kaedah Mengasingkan Campuran: Guna Magnet": "audio/6b05654c343c.mp3",
"Kalau bersepah di lantai, komponen boleh hilang dan memijaknya akan sangat menyakitkan kaki!": "audio/60574e9e08a1.mp3",
"Kalau cuai, bikar boleh pecah dan tangan awak terluka!": "audio/622c6f6920c0.mp3",
"Kalau letak garam dalam air teh, lama-lama hilang. Kenapa?": "audio/5b12f476a5a7.mp3",
"Kalau terlangkau satu langkah, robot awak mungkin tak boleh berdiri seimbang!": "audio/96aad883b534.mp3",
"Kami Berbeza!": "audio/1eda9fe112a5.mp3",
"Kami Serupa, Kami Berbeza": "audio/25080eefe730.mp3",
"Kami Serupa, Kami Berbeza: Kami Berbeza!": "audio/82261c027140.mp3",
"Katak bertelur ratusan biji telur sebab kebarangkalian telurnya dimakan musuh sangat tinggi.": "audio/e17a36b0292b.mp3",
"Kawasan air mengalir yang jatuh dari tebing tinggi dipanggil Air Terjun! ️": "audio/29dac6a2174a.mp3",
"Ke manakah air sungai mengalir akhirnya?": "audio/9be5a7da3a4d.mp3",
"Kejelasan Bayang-bayang": "audio/9617b4d40286.mp3",
"Kejelasan Bayang-bayang: Legap vs Lut Sinar": "audio/1f4bf37721ec.mp3",
"Kemahiran Manipulatif": "audio/a8b4b3e027a3.mp3",
"Kemahiran Manipulatif: Pegang dengan Cermat": "audio/3a2bbc9c6f6e.mp3",
"Kemas Semula": "audio/1cc748f65dfe.mp3",
"Kenali Komponen Elektrik": "audio/d6a72e5f2e20.mp3",
"Kenali Komponen Elektrik: Bateri, Suis, Mentol": "audio/37eaff3f16ff.mp3",
"Kenapa bila beli mainan baru, ada satu buku kecil disertakan?": "audio/f0acb8c7ead7.mp3",
"Kenapa tumbuh-tumbuhan sangat penting pada manusia & haiwan?": "audio/8f90864e3b4b.mp3",
"Kenapa warna rambut atau muka awak iras-iras mak ayah awak?": "audio/e79bed9706ee.mp3",
"Kepentingan Tumbuh-tumbuhan": "audio/7e419d04ac9c.mp3",
"Kepentingan Tumbuh-tumbuhan: Sumber Utama": "audio/12853b5e9b06.mp3",
"Keperluan Asas Biji Benih Bercambah": "audio/928ae98c63e7.mp3",
"Keperluan Asas Biji Benih Bercambah: Air, Udara, Suhu": "audio/a9293790734a.mp3",
"Keperluan Asas Tumbesaran": "audio/3fdc95f1ef38.mp3",
"Keperluan Asas Tumbesaran: Air, Cahaya & Udara": "audio/45e1e20f711b.mp3",
"Keselamatan Utama": "audio/c3c581e37c1b.mp3",
"Kita boleh cipta patung kertas sendiri. Suluh lampu dari depan, dan bayangnya akan jatuh ke skrin layar!": "audio/c46dd0f35acf.mp3",
"Kita boleh cipta patung kertas sendiri. Suluh lampu dari depan, dan bayangnya akan jatuh ke skrin layar!  Wayang Kulit adalah permainan tradisional Melayu yang guna konsep bayang-bayang!": "audio/2bfbf5b898dd.mp3",
"Kita boleh hasilkan roket kertas menggunakan belon. Udara yang keluar menolak belon meluncur laju ke depan.": "audio/e54338e10e72.mp3",
"Kita boleh hasilkan roket kertas menggunakan belon. Udara yang keluar menolak belon meluncur laju ke depan.  Daya tolakan udara inilah yang digunakan oleh roket angkasa lepas sebenar!": "audio/51aca9dd19c9.mp3",
"Kita guna magnet. Kaedah lain: Menyisih, Mengayak, Menuras (guna penapis), dan Mengapung.": "audio/dc3c6ca0eeb6.mp3",
"Kita guna magnet. Kaedah lain: Menyisih, Mengayak, Menuras (guna penapis), dan Mengapung.  Mengayak sangat bagus untuk asingkan pasir kasar daripada gula halus! ️": "audio/c5c466f28604.mp3",
"Kita guna pembaris atau pita pengukur. Tak boleh sekadar teka-teka!": "audio/15a1ce0ed2df.mp3",
"Kita guna pembaris atau pita pengukur. Tak boleh sekadar teka-teka!  Zaman dulu, orang ukur guna jengkal tangan. Tapi tangan orang tak sama besar, jadi selalu salah!": "audio/3464e32f8401.mp3",
"Kita tak boleh nampak udara. Di mana ia wujud?": "audio/bce810cbdc54.mp3",
"Kitar Hidup Haiwan": "audio/68c277949aaa.mp3",
"Kitar Hidup Haiwan: 4 Peringkat": "audio/76c05e938730.mp3",
"Kitaran Air Semula Jadi": "audio/3e4961a4f946.mp3",
"Kitaran Air Semula Jadi: Wap Air Naik": "audio/b2ec94029e75.mp3",
"Kitaran air memastikan bekalan air di Bumi tak pernah habis!": "audio/70ed8faec590.mp3",
"Klip kertas besi bercampur dalam tepung. Macam mana nak asingkan?": "audio/1191779bdc25.mp3",
"Konduktor dan Penebat": "audio/7280e6c3c40f.mp3",
"Konduktor dan Penebat: Konduktor vs Penebat": "audio/742b6010e12e.mp3",
"Konduktor vs Penebat": "audio/4bf432ea8113.mp3",
"Kucing ada mata istimewa yang boleh melihat dalam gelap lebih baik dari manusia!": "audio/5659fbd1aff5.mp3",
"Kucing dan arnab beranak banyak (beberapa ekor sekaligus). Paus dan lembu beranak sedikit (biasanya seekor).": "audio/4bc15f7157e9.mp3",
"Kucing dan arnab beranak banyak (beberapa ekor sekaligus). Paus dan lembu beranak sedikit (biasanya seekor).  Arnab boleh lahirkan sehingga 14 ekor anak dalam satu masa!": "audio/6f530942a3cc.mp3",
"Kucing dan harimau dalam kumpulan yang sama. Kenapa ya?": "audio/4e297400353b.mp3",
"Kucing dan ikan lumba-lumba melahirkan anak. Siapa beranak lebih banyak?": "audio/87b0b611ab51.mp3",
"Kucing!": "audio/07cafc8922c5.mp3",
"Lakaran & Carta": "audio/198e3f3ca78e.mp3",
"Legap vs Lut Sinar": "audio/afa9db0ee29b.mp3",
"Lepas mahir, awak bebas berimaginasi! Awak boleh reka bentuk model unik sendiri seperti kereta terbang.": "audio/b648ad5fbda8.mp3",
"Lepas mahir, awak bebas berimaginasi! Awak boleh reka bentuk model unik sendiri seperti kereta terbang.  Perekacipta tersohor dunia bermula dengan selalu bermain mencantum barang baharu.": "audio/12f21f19a410.mp3",
"Litar Lengkap": "audio/0408891d85c7.mp3",
"Litar Tak Lengkap": "audio/8b9fe45ba2da.mp3",
"Litar asas menggunakan Sel Kering (bateri), Suis, dan Mentol, disambung dengan wayar.": "audio/ac4d40cdd0cc.mp3",
"Litar asas menggunakan Sel Kering (bateri), Suis, dan Mentol, disambung dengan wayar.  Bateri bersaiz AA yang kita selalu guna tu ialah contoh \"Sel Kering\".": "audio/76fd9019f62c.mp3",
"Litar terbuka ibarat jambatan putus, arus elektrik tak boleh melintas!": "audio/58579330db02.mp3",
"Macam mana bayang-bayang hitam tu boleh terhasil?": "audio/5e4e8ff5a307.mp3",
"Macam mana hujan boleh terjadi?": "audio/bdfc213ffe21.mp3",
"Macam mana jumlah manusia makin bertambah di Bumi?": "audio/2a1a2fa0fab1.mp3",
"Macam mana nak tahu berapa panjang meja ini dengan tepat?": "audio/3f964bd2b281.mp3",
"Makanan berkhasiat macam susu boleh bantu awak membesar dengan sihat!": "audio/57baaf6b2c37.mp3",
"Makin Tinggi": "audio/d594aa666b88.mp3",
"Makin dekat objek dengan lampu, makin BESAR bayangnya!": "audio/c36b7bc0872b.mp3",
"Manual menerangkan jenis komponen dan langkah-langkah memasang model secara teratur dan betul.": "audio/389c50bc1691.mp3",
"Manual menerangkan jenis komponen dan langkah-langkah memasang model secara teratur dan betul.  Jurutera sebenar pun merujuk \"manual\" atau pelan lantai sebelum membina rumah! ️": "audio/ed3e56a06950.mp3",
"Manusia Membiak": "audio/4ed0e00535c8.mp3",
"Manusia Membiak: Melahirkan Anak": "audio/d07a07f9573a.mp3",
"Manusia adalah kumpulan hidupan yang membiak dengan cara melahirkan anak.": "audio/89030842b7ae.mp3",
"Manusia adalah kumpulan hidupan yang membiak dengan cara melahirkan anak.  Haiwan seperti kucing dan lembu pun membiak dengan cara yang sama!": "audio/5d8eb3b2c1ef.mp3",
"Mata untuk melihat, telinga mendengar, hidung menghidu, lidah merasa, dan kulit menyentuh.": "audio/6dd01ab47321.mp3",
"Mata untuk melihat, telinga mendengar, hidung menghidu, lidah merasa, dan kulit menyentuh.  Pemerhatian ialah langkah pertama bagi setiap saintis yang hebat!": "audio/44cd87b7f779.mp3",
"Matahari ialah sumber cahaya utama semula jadi. Selain itu kita ada lampu dan api.": "audio/74f58cdd63b5.mp3",
"Matahari ialah sumber cahaya utama semula jadi. Selain itu kita ada lampu dan api.  Matahari sebenarnya adalah sebiji bintang gergasi yang sangat panas! ⭐": "audio/14e9b3281fcd.mp3",
"Matahari sebenarnya adalah sebiji bintang gergasi yang sangat panas! ⭐": "audio/01135d155fc6.mp3",
"Matahari!": "audio/45b506a66b3f.mp3",
"Melahirkan Anak": "audio/850a0c5d6e5a.mp3",
"Membina Litar Elektrik": "audio/0b18712009e9.mp3",
"Membina Litar Elektrik: Litar Lengkap": "audio/19902c7cb9b6.mp3",
"Membina model melatih otak awak supaya lebih kreatif dan bijak menyelesaikan masalah!": "audio/bd9f6ae93f04.mp3",
"Memerhati": "audio/7d1ee190b4a3.mp3",
"Memerhati: Guna 5 Deria": "audio/1a06435e24a2.mp3",
"Mencipta Permainan Wayang Kertas": "audio/f03a2201d109.mp3",
"Mencipta Permainan Wayang Kertas: Guna Cahaya": "audio/606d6d86c160.mp3",
"Mencipta Roket Angin": "audio/4ed1de7cad58.mp3",
"Mencipta Roket Angin: Boleh!": "audio/12348237873d.mp3",
"Mengapakah Mentol Tidak Menyala?": "audio/d08288f97799.mp3",
"Mengapakah Mentol Tidak Menyala?: Litar Tak Lengkap": "audio/bba3a02d4648.mp3",
"Mengayak sangat bagus untuk asingkan pasir kasar daripada gula halus! ️": "audio/de6dd3a4c660.mp3",
"Mengelas": "audio/08993bd54ef1.mp3",
"Mengelas bermaksud mengasingkan benda ikut sifatnya. Contoh: Asingkan haiwan berkaki empat!": "audio/f805004cbc22.mp3",
"Mengelas bermaksud mengasingkan benda ikut sifatnya. Contoh: Asingkan haiwan berkaki empat!  Cuba kelaskan rakan di kelas awak. Ada yang pakai cermin mata, ada yang tidak!": "audio/f7c1006b403d.mp3",
"Mengelas: Ciri yang Sama": "audio/c942e5dd7be1.mp3",
"Mengenali Komponen dalam Manual Bergambar": "audio/f1830af140ec.mp3",
"Mengenali Komponen dalam Manual Bergambar: Buku Manual": "audio/9ff273227bde.mp3",
"Mengukur dan Menggunakan Nombor": "audio/303fd635ef4e.mp3",
"Mengukur dan Menggunakan Nombor: Guna Alat Betul": "audio/5a83a6f5e571.mp3",
"Mentol hanya akan menyala jika litar disambung lengkap dan suis DITUTUP (ON).": "audio/387729291221.mp3",
"Mentol hanya akan menyala jika litar disambung lengkap dan suis DITUTUP (ON).  Perkataan \"Tutup Suis\" dalam sains bermaksud menyambungkan litar. Jangan keliru ya!": "audio/d7a950d11ed8.mp3",
"Menuju Laut": "audio/0533a62c74ee.mp3",
"Menyambung Arus": "audio/f559d86c12a7.mp3",
"Mesti ke sentiasa ikut manual?": "audio/95796654ea81.mp3",
"Milo lambat nak hancur! Apa rahsia nak bagi bahan cepat larut?": "audio/98412e5098f2.mp3",
"Mungkin suis masih TERBUKA, sel kering habis tenaga, mentol rosak, atau pemasangan wayar salah.": "audio/410c87b5ba1f.mp3",
"Mungkin suis masih TERBUKA, sel kering habis tenaga, mentol rosak, atau pemasangan wayar salah.  Litar terbuka ibarat jambatan putus, arus elektrik tak boleh melintas!": "audio/07868a11f815.mp3",
"Paku besi ialah KONDUKTOR (mengalirkan arus, mentol nyala). Pemadam ialah PENEBAT (menghalang arus, mentol padam).": "audio/b9b650eb49d2.mp3",
"Paku besi ialah KONDUKTOR (mengalirkan arus, mentol nyala). Pemadam ialah PENEBAT (menghalang arus, mentol padam).  Plastik membalut wayar elektrik di rumah awak ialah Penebat supaya awak tak terkena renjatan!": "audio/e36bca97cc90.mp3",
"Pandai!": "audio/f3e6be918dd7.mp3",
"Patuhi dan Fahami Peraturan Bilik Sains": "audio/bf077b5e32a5.mp3",
"Patuhi dan Fahami Peraturan Bilik Sains: Keselamatan Utama": "audio/3d7f5bd82425.mp3",
"Paus adalah haiwan lautan tapi ia BUKAN bertelur, ia melahirkan anak!": "audio/4b7e6d7be560.mp3",
"Pegang dengan Cermat": "audio/4f4bf2b07fab.mp3",
"Pemerhatian ialah langkah pertama bagi setiap saintis yang hebat!": "audio/3482cab56915.mp3",
"Penyu dan katak bertelur sangat banyak (beratus biji)! Tapi burung penguin hanya bertelur sedikit.": "audio/f4e4922a6e5e.mp3",
"Penyu dan katak bertelur sangat banyak (beratus biji)! Tapi burung penguin hanya bertelur sedikit.  Katak bertelur ratusan biji telur sebab kebarangkalian telurnya dimakan musuh sangat tinggi.": "audio/a63657dc99b1.mp3",
"Peraturan ini wujud supaya tiada siapa cedera terkena bahan kimia!": "audio/21867ec35484.mp3",
"Perekacipta tersohor dunia bermula dengan selalu bermain mencantum barang baharu.": "audio/16cb383ae538.mp3",
"Perjalanan air ini sangat panjang dan menyokong kehidupan banyak haiwan darat!": "audio/8c94f4261770.mp3",
"Perkataan \"Tutup Suis\" dalam sains bermaksud menyambungkan litar. Jangan keliru ya!": "audio/49b795d46f0c.mp3",
"Permainan Bayang-bayang": "audio/ee60558adf0b.mp3",
"Permainan Bayang-bayang: Boleh!": "audio/ceed6b9e6852.mp3",
"Pernah tengok wayang kulit?": "audio/c695950f252a.mp3",
"Pewarisan": "audio/e1464ef5f8c9.mp3",
"Pewarisan ini menjadikan setiap keluarga nampak serupa tapi tak sama!": "audio/d3e20e15c373.mp3",
"Pewarisan: Diwarisi": "audio/96a51760c778.mp3",
"Plastik membalut wayar elektrik di rumah awak ialah Penebat supaya awak tak terkena renjatan!": "audio/2e0e23bcf0f6.mp3",
"Pokok WAJIB perlukan Cahaya Matahari, Air, dan Udara untuk membuat makanannya sendiri.": "audio/6ea94589d452.mp3",
"Pokok WAJIB perlukan Cahaya Matahari, Air, dan Udara untuk membuat makanannya sendiri.  Baja adalah nutrien tambahan supaya dia tumbuh lebih gemuk dan subur!": "audio/25ea91c62bc2.mp3",
"Pokok beri kita habitat (tempat tinggal), udara (oksigen), makanan, dan ubat-ubatan.": "audio/3e6ee1a79e44.mp3",
"Pokok beri kita habitat (tempat tinggal), udara (oksigen), makanan, dan ubat-ubatan.  Buku nota dan pensel awak pun asalnya diperbuat daripada kayu pokok!": "audio/25757697a0fc.mp3",
"Proses pertukaran bentuk yang sangat menakjubkan ini dipanggil \"Metamorfosis\".": "audio/ba6a73a7ff99.mp3",
"Saintis tak semestinya bercakap. Mereka lukis lakaran, buat jadual, dan carta supaya mudah faham!": "audio/4bfd25e5471b.mp3",
"Saintis tak semestinya bercakap. Mereka lukis lakaran, buat jadual, dan carta supaya mudah faham!  Awak pun sedang berkomunikasi bila lukis gambar pokok untuk kawan!": "audio/cabd0b9becc3.mp3",
"Saiz Bertambah": "audio/b16791519fec.mp3",
"Saiz bayang berubah bergantung jarak lampu dengan objek. Bentuk pula ikut kedudukan objek.": "audio/bb6a72aca3c5.mp3",
"Saiz bayang berubah bergantung jarak lampu dengan objek. Bentuk pula ikut kedudukan objek.  Makin dekat objek dengan lampu, makin BESAR bayangnya!": "audio/4f16f73f7551.mp3",
"Salah": "audio/fd08f03524ae.mp3",
"Sama hitam ke bayang-bayang plastik jernih berbanding buku tebal?": "audio/1dc5cd0e397a.mp3",
"Saya Kreatif": "audio/84620b034c55.mp3",
"Saya Kreatif: Tak Semestinya!": "audio/e3dbea747d9c.mp3",
"Saya Membesar": "audio/632e808f8bb8.mp3",
"Saya Membesar: Saiz Bertambah": "audio/8d9c848c4286.mp3",
"Saya dah pasang wayar, kenapa mentol masih tak nyala?": "audio/bc87b714c570.mp3",
"Sebab ciri-ciri seperti jenis rambut, warna kulit dan warna mata \"diwarisi\" dari keturunan kita.": "audio/247b46e10e50.mp3",
"Sebab ciri-ciri seperti jenis rambut, warna kulit dan warna mata \"diwarisi\" dari keturunan kita.  Pewarisan ini menjadikan setiap keluarga nampak serupa tapi tak sama!": "audio/977faad8e43a.mp3",
"Sebutkan langkah-langkah pokok tomato membesar.": "audio/5055f44864c0.mp3",
"Selain bercakap, macam mana saintis kongsi rekod?": "audio/7ff5cafbaa85.mp3",
"Semua anak haiwan rupa sama macam ibunya kah bila lahir?": "audio/04d80956bd9f.mp3",
"Senang Melihat": "audio/9a872962447a.mp3",
"Set binaan (seperti Lego) mempunyai komponen berbeza bentuk untuk dicantumkan menjadi pelbagai model menarik.": "audio/b7096727e584.mp3",
"Set binaan (seperti Lego) mempunyai komponen berbeza bentuk untuk dicantumkan menjadi pelbagai model menarik.  Membina model melatih otak awak supaya lebih kreatif dan bijak menyelesaikan masalah!": "audio/cc65d5eadb08.mp3",
"Setiap Orang Unik": "audio/69da88a11e69.mp3",
"Suis menyambung atau memutuskan arus. Mentol hasilkan cahaya. Sel Kering beri tenaga elektrik.": "audio/656198eb4582.mp3",
"Suis menyambung atau memutuskan arus. Mentol hasilkan cahaya. Sel Kering beri tenaga elektrik.  Tanpa sel kering, litar lengkap sekalipun takkan boleh menyalakan mentol.": "audio/cda64b81f725.mp3",
"Sumber Air Semula Jadi": "audio/50e2443cfcbe.mp3",
"Sumber Air Semula Jadi: Hujan, Sungai, Laut": "audio/0d0cf8fca7ad.mp3",
"Sumber Cahaya": "audio/0006e6548a7a.mp3",
"Sumber Cahaya: Matahari!": "audio/e1731db3751d.mp3",
"Sumber Utama": "audio/531888df46ea.mp3",
"Sumber air semula jadi kita ialah hujan, sungai, tasik, laut, dan mata air.": "audio/0ee91cecf89e.mp3",
"Sumber air semula jadi kita ialah hujan, sungai, tasik, laut, dan mata air.  Walaupun laut sangat besar, airnya masin dan tak boleh diminum terus!": "audio/9d6704a14d44.mp3",
"Tak Sama!": "audio/203511a4be8a.mp3",
"Tak Semestinya!": "audio/c76c38da17d1.mp3",
"Tak apa, cuba lagi ya!": "audio/a944d60ed9e8.mp3",
"Tak sama! Objek legap (buku) hasilkan bayang jelas. Objek lut sinar (plastik jernih) tiada bayang!": "audio/dbffba343a17.mp3",
"Tak sama! Objek legap (buku) hasilkan bayang jelas. Objek lut sinar (plastik jernih) tiada bayang!  Kaca tingkap rumah adalah lut sinar supaya cahaya penuh boleh masuk.": "audio/2ca66b77ff95.mp3",
"Tanpa sel kering, litar lengkap sekalipun takkan boleh menyalakan mentol.": "audio/43f55066371d.mp3",
"Telur  Beluncas (Larva)  Kepompong (Pupa)  Rama-rama dewasa!": "audio/41e3aaca9217.mp3",
"Telur  Beluncas (Larva)  Kepompong (Pupa)  Rama-rama dewasa!  Proses pertukaran bentuk yang sangat menakjubkan ini dipanggil \"Metamorfosis\".": "audio/4afa90ad1107.mp3",
"Terang dan Gelap": "audio/dd1049738c88.mp3",
"Terang dan Gelap: Senang Melihat": "audio/225aa590cb54.mp3",
"Tidak. Air sentiasa mengalir dari kawasan tinggi (gunung) menuju ke kawasan yang lebih rendah (laut).": "audio/e321e3152319.mp3",
"Tidak. Air sentiasa mengalir dari kawasan tinggi (gunung) menuju ke kawasan yang lebih rendah (laut).  Kawasan air mengalir yang jatuh dari tebing tinggi dipanggil Air Terjun! ️": "audio/199996258ac4.mp3",
"Tumbesaran Berbeza": "audio/35cb695455be.mp3",
"Tumbesaran Berbeza: Setiap Orang Unik": "audio/7521d244fa1f.mp3",
"Tumbesaranku": "audio/68edae74d72f.mp3",
"Tumbesaranku: Makin Tinggi": "audio/26291bcdf748.mp3",
"Udara": "audio/3874a9a3daee.mp3",
"Udara Bergerak": "audio/5484816fce8f.mp3",
"Udara Bergerak: Angin!": "audio/098a7c6108f0.mp3",
"Udara ada di mana-mana sahaja, termasuk dalam air dan tanah! Udara mengandungi pelbagai gas seperti oksigen.": "audio/7cc9efce5464.mp3",
"Udara ada di mana-mana sahaja, termasuk dalam air dan tanah! Udara mengandungi pelbagai gas seperti oksigen.  Ikan di dalam laut pun bernafas menggunakan udara (oksigen) yang terlarut dalam air!": "audio/0a4d97138770.mp3",
"Udara yang bergerak dipanggil ANGIN. Angin membantu menerbangkan layang-layang dan mengeringkan baju.": "audio/f5ad7934651f.mp3",
"Udara yang bergerak dipanggil ANGIN. Angin membantu menerbangkan layang-layang dan mengeringkan baju.  Angin yang terlalu kuat dipanggil ribut dan boleh menumbangkan pokok!": "audio/566a91675f06.mp3",
"Udara: Di Sekeliling Kita": "audio/cb0a2a7976b2.mp3",
"Urutan Tumbesaran Tumbuh-tumbuhan": "audio/bd03ca6c9b11.mp3",
"Urutan Tumbesaran Tumbuh-tumbuhan: Dari Benih ke Buah": "audio/b656f02c8f5b.mp3",
"Wah, hebatnya!": "audio/d03f1ba18219.mp3",
"Waktu terang (ada cahaya) memudahkan kita melihat. Waktu gelap menyukarkan pemerhatian.": "audio/4a6d3c4af2b9.mp3",
"Waktu terang (ada cahaya) memudahkan kita melihat. Waktu gelap menyukarkan pemerhatian.  Kucing ada mata istimewa yang boleh melihat dalam gelap lebih baik dari manusia!": "audio/f5f035516dab.mp3",
"Walaupun laut sangat besar, airnya masin dan tak boleh diminum terus!": "audio/80e8e3aff621.mp3",
"Wap Air Naik": "audio/d66fe5951028.mp3",
"Wayang Kulit adalah permainan tradisional Melayu yang guna konsep bayang-bayang!": "audio/413344a3aa98.mp3",
"Zaman dulu, orang ukur guna jengkal tangan. Tapi tangan orang tak sama besar, jadi selalu salah!": "audio/c72ab692b3af.mp3"
};
