const unitNotesData = {
    'unit1': [
        { frontEmoji: '<img src="images/fox_memerhati.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Memerhati', frontQuestion: 'Cuba tengok sekeliling awak! Kita guna deria apa untuk kenal pasti benda?', backEmoji: '<img src="images/bg_observing.jpg?v=2" class="flashcard-bg-img">', backTitle: 'Guna 5 Deria', backAnswer: 'Mata untuk melihat, telinga mendengar, hidung menghidu, lidah merasa, dan kulit menyentuh.', trivia: 'Pemerhatian ialah langkah pertama bagi setiap saintis yang hebat! 🌸' },
        { frontEmoji: '<img src="images/fox_mengelas.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Mengelas', frontQuestion: 'Kucing dan harimau dalam kumpulan yang sama. Kenapa ya?', backEmoji: '<img src="images/bg_classifying.jpg?v=2" class="flashcard-bg-img">', backTitle: 'Ciri yang Sama', backAnswer: 'Mengelas bermaksud mengasingkan benda ikut sifatnya. Contoh: Asingkan haiwan berkaki empat!', trivia: 'Cuba kelaskan rakan di kelas awak. Ada yang pakai cermin mata, ada yang tidak! 👓' },
        { frontEmoji: '<img src="images/fox_mengukur.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Mengukur dan Menggunakan Nombor', frontQuestion: 'Macam mana nak tahu berapa panjang meja ini dengan tepat?', backEmoji: '<img src="images/bg_measuring.jpg?v=2" class="flashcard-bg-img">', backTitle: 'Guna Alat Betul', backAnswer: 'Kita guna pembaris atau pita pengukur. Tak boleh sekadar teka-teka!', trivia: 'Zaman dulu, orang ukur guna jengkal tangan. Tapi tangan orang tak sama besar, jadi selalu salah! 🤭' },
        { frontEmoji: '<img src="images/fox_berkomunikasi.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Berkomunikasi', frontQuestion: 'Selain bercakap, macam mana saintis kongsi rekod?', backEmoji: '<img src="images/bg_communicating.jpg?v=2" class="flashcard-bg-img">', backTitle: 'Lakaran & Carta', backAnswer: 'Saintis tak semestinya bercakap. Mereka lukis lakaran, buat jadual, dan carta supaya mudah faham!', trivia: 'Awak pun sedang berkomunikasi bila lukis gambar pokok untuk kawan! 🎨' },
        { frontEmoji: '<img src="images/fox_manipulatif.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Kemahiran Manipulatif', frontQuestion: 'Bila guna bikar kaca, kita kena pegang macam mana?', backEmoji: '<img src="images/bg_manipulative.jpg?v=2" class="flashcard-bg-img">', backTitle: 'Pegang dengan Cermat', backAnswer: 'Gunakan alatan dengan betul, lakar spesimen, bersihkan alat, dan simpan dengan selamat.', trivia: 'Kalau cuai, bikar boleh pecah dan tangan awak terluka! 🩸' }
    ],
    'unit2': [
        { frontEmoji: '<img src="images/fox_peraturan.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Patuhi dan Fahami Peraturan Bilik Sains', frontQuestion: 'Apakah peraturan paling penting bila masuk Bilik Sains?', backEmoji: '<img src="images/bg_science_lab.jpg?v=2" class="flashcard-bg-img">', backTitle: 'Keselamatan Utama', backAnswer: 'Beratur sebelum masuk, dilarang makan/minum, lapor kecederaan, dan buang sisa di tempat betul.', trivia: 'Peraturan ini wujud supaya tiada siapa cedera terkena bahan kimia! 🧪' }
    ],
    'unit3': [
        { frontEmoji: '<img src="images/fox_membiak.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Manusia Membiak', frontQuestion: 'Macam mana jumlah manusia makin bertambah di Bumi?', backEmoji: '<img src="images/bg_membiak.jpg" class="flashcard-bg-img">', backTitle: 'Melahirkan Anak', backAnswer: 'Manusia adalah kumpulan hidupan yang membiak dengan cara melahirkan anak.', trivia: 'Haiwan seperti kucing dan lembu pun membiak dengan cara yang sama! 🐄' },
        { frontEmoji: '<img src="images/fox_membesar.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Saya Membesar', frontQuestion: 'Apa bukti yang menunjukkan awak semakin membesar?', backEmoji: '<img src="images/bg_membesar.jpg" class="flashcard-bg-img">', backTitle: 'Saiz Bertambah', backAnswer: 'Bila kita membesar, saiz badan, berat, dan tinggi kita akan bertambah!', trivia: 'Cuba pakai baju masa umur awak 2 tahun. Mesti dah ketat kan? 😂' },
        { frontEmoji: '<img src="images/fox_tumbesaran.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Tumbesaran Berbeza', frontQuestion: 'Awak dengan kawan awak umur sama, tapi kenapa tinggi berbeza?', backEmoji: '<img src="images/bg_tumbesaran.jpg" class="flashcard-bg-img">', backTitle: 'Setiap Orang Unik', backAnswer: 'Kadar tumbesaran manusia berbeza-beza. Ada kawan yang tinggi, ada yang rendah sedikit. Itu normal!', trivia: 'Adik-beradik pun ada yang tinggi, ada yang rendah, walaupun mak ayah sama! 📏' },
        { frontEmoji: '<img src="images/fox_pewarisan.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Pewarisan', frontQuestion: 'Kenapa warna rambut atau muka awak iras-iras mak ayah awak?', backEmoji: '<img src="images/bg_pewarisan.jpg" class="flashcard-bg-img">', backTitle: 'Diwarisi', backAnswer: 'Sebab ciri-ciri seperti jenis rambut, warna kulit dan warna mata "diwarisi" dari keturunan kita.', trivia: 'Pewarisan ini menjadikan setiap keluarga nampak serupa tapi tak sama! ✨' }
    ],
    'unit4': [
        { frontEmoji: '<img src="images/fox_haiwan_membiak.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Haiwan Membiak', frontQuestion: 'Ayam dan lembu, dua-dua ada anak. Macam mana caranya?', backEmoji: '<img src="images/bg_haiwan_membiak.jpg" class="flashcard-bg-img">', backTitle: 'Bertelur vs Beranak', backAnswer: 'Haiwan membiak dengan dua cara: Ada yang bertelur (ayam), ada yang melahirkan anak (lembu).', trivia: 'Paus adalah haiwan lautan tapi ia BUKAN bertelur, ia melahirkan anak! 🐳' },
        { frontEmoji: '<img src="images/fox_bertelur.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Bertelur Sedikit, Bertelur Banyak', frontQuestion: 'Adakah semua haiwan bertelur banyak sekaligus?', backEmoji: '<img src="images/bg_bertelur.jpg" class="flashcard-bg-img">', backTitle: 'Tak Sama!', backAnswer: 'Penyu dan katak bertelur sangat banyak (beratus biji)! Tapi burung penguin hanya bertelur sedikit.', trivia: 'Katak bertelur ratusan biji telur sebab kebarangkalian telurnya dimakan musuh sangat tinggi. 😱' },
        { frontEmoji: '<img src="images/fox_beranak.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Beranak Sedikit, Beranak Banyak', frontQuestion: 'Kucing dan ikan lumba-lumba melahirkan anak. Siapa beranak lebih banyak?', backEmoji: '<img src="images/bg_beranak.jpg" class="flashcard-bg-img">', backTitle: 'Kucing!', backAnswer: 'Kucing dan arnab beranak banyak (beberapa ekor sekaligus). Paus dan lembu beranak sedikit (biasanya seekor).', trivia: 'Arnab boleh lahirkan sehingga 14 ekor anak dalam satu masa! 🐇' },
        { frontEmoji: '<img src="images/fox_serupa.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Kami Serupa, Kami Berbeza', frontQuestion: 'Semua anak haiwan rupa sama macam ibunya kah bila lahir?', backEmoji: '<img src="images/bg_serupa.jpg" class="flashcard-bg-img">', backTitle: 'Kami Berbeza!', backAnswer: 'Anak lembu serupa ibunya. Tapi anak rama-rama (beluncas) atau katak (berudu) lansung TAK SAMA macam ibunya!', trivia: 'Berudu bernafas guna insang dalam air sebelum jadi katak yang bernafas guna paru-paru! 💧', image: 'images/frog.png?v=4' },
        { frontEmoji: '<img src="images/fox_kitar.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Kitar Hidup Haiwan', frontQuestion: 'Apakah turutan kitar hidup seekor rama-rama?', backEmoji: '<img src="images/bg_kitar.jpg" class="flashcard-bg-img">', backTitle: '4 Peringkat', backAnswer: 'Telur ➔ Beluncas (Larva) ➔ Kepompong (Pupa) ➔ Rama-rama dewasa!', trivia: 'Proses pertukaran bentuk yang sangat menakjubkan ini dipanggil "Metamorfosis". 🌟', image: 'images/butterfly.png?v=4' }
    ],
    'unit5': [
        { frontEmoji: '<img src="images/fox_kepentingan.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Kepentingan Tumbuh-tumbuhan', frontQuestion: 'Kenapa tumbuh-tumbuhan sangat penting pada manusia & haiwan?', backEmoji: '<img src="images/bg_kepentingan.jpg" class="flashcard-bg-img">', backTitle: 'Sumber Utama', backAnswer: 'Pokok beri kita habitat (tempat tinggal), udara (oksigen), makanan, dan ubat-ubatan.', trivia: 'Buku nota dan pensel awak pun asalnya diperbuat daripada kayu pokok! 📝' },
        { frontEmoji: '<img src="images/fox_biji_benih.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Keperluan Asas Biji Benih Bercambah', frontQuestion: 'Biji benih perlu apa untuk mula pecah dan keluar akar?', backEmoji: '<img src="images/bg_biji_benih.jpg" class="flashcard-bg-img">', backTitle: 'Air, Udara, Suhu', backAnswer: 'Biji benih HANYA perlukan Air, Udara dan Suhu yang sesuai untuk bercambah. (Cahaya belum perlu).', trivia: 'Biji benih tak perlukan matahari waktu mula bercambah sebab ia tertimbus dalam tanah gelap! 🌑' },
        { frontEmoji: '<img src="images/fox_tumbesaranku.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Tumbesaranku', frontQuestion: 'Apa yang berubah bila anak pokok makin membesar?', backEmoji: '<img src="images/bg_tumbesaranku.jpg" class="flashcard-bg-img">', backTitle: 'Makin Tinggi', backAnswer: 'Bilangan daun makin banyak, saiz daun makin besar, lilitan batang makin lebar, dan pokok makin tinggi.', trivia: 'Ada pokok balak yang lilitan batangnya sangat besar sampaikan 10 orang pegang tangan tak cukup! 🌲' },
        { frontEmoji: '<img src="images/fox_urutan.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Urutan Tumbesaran Tumbuh-tumbuhan', frontQuestion: 'Sebutkan langkah-langkah pokok tomato membesar.', backEmoji: '<img src="images/bg_urutan.jpg" class="flashcard-bg-img">', backTitle: 'Dari Benih ke Buah', backAnswer: 'Biji Benih ➔ Biji Benih Bercambah ➔ Anak Pokok ➔ Pokok Berbunga ➔ Pokok Berbuah!', trivia: 'Bunga pokok sebenarnya bertukar menjadi buah selepas proses pendebungaan! 🐝' },
        { frontEmoji: '<img src="images/fox_keperluan.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Keperluan Asas Tumbesaran', frontQuestion: 'Bila dah jadi pokok, apa dia perlukan untuk hidup sihat?', backEmoji: '<img src="images/bg_keperluan.jpg" class="flashcard-bg-img">', backTitle: 'Air, Cahaya & Udara', backAnswer: 'Pokok WAJIB perlukan Cahaya Matahari, Air, dan Udara untuk membuat makanannya sendiri.', trivia: 'Baja adalah nutrien tambahan supaya dia tumbuh lebih gemuk dan subur! 🥗' }
    ],
    'unit6': [
        { frontEmoji: '<img src="images/fox_sumber_cahaya.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Sumber Cahaya', frontQuestion: 'Dari manakah datangnya cahaya di Bumi ini?', backEmoji: '<img src="images/bg_sumber_cahaya.jpg" class="flashcard-bg-img">', backTitle: 'Matahari!', backAnswer: 'Matahari ialah sumber cahaya utama semula jadi. Selain itu kita ada lampu dan api.', trivia: 'Matahari sebenarnya adalah sebiji bintang gergasi yang sangat panas! ⭐' },
        { frontEmoji: '<img src="images/fox_terang_gelap.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Terang dan Gelap', frontQuestion: 'Apa beza aktiviti waktu terang dan waktu gelap?', backEmoji: '<img src="images/bg_terang_gelap.jpg" class="flashcard-bg-img">', backTitle: 'Senang Melihat', backAnswer: 'Waktu terang (ada cahaya) memudahkan kita melihat. Waktu gelap menyukarkan pemerhatian.', trivia: 'Kucing ada mata istimewa yang boleh melihat dalam gelap lebih baik dari manusia! 🐈' },
        { frontEmoji: '<img src="images/fox_bayang.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Bayang-bayang', frontQuestion: 'Macam mana bayang-bayang hitam tu boleh terhasil?', backEmoji: '<img src="images/bg_bayang.jpg" class="flashcard-bg-img">', backTitle: 'Cahaya Dihalang', backAnswer: 'Bayang-bayang terbentuk apabila pergerakan cahaya lurus DIHALANG oleh suatu objek.', trivia: 'Bila awak halang jalan cahaya, kawasan di belakang awak yang tak kena cahaya tulah bayang! 🕵️', image: 'images/shadow.png?v=4' },
        { frontEmoji: '<img src="images/fox_kejelasan.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Kejelasan Bayang-bayang', frontQuestion: 'Sama hitam ke bayang-bayang plastik jernih berbanding buku tebal?', backEmoji: '<img src="images/bg_kejelasan.jpg" class="flashcard-bg-img">', backTitle: 'Legap vs Lut Sinar', backAnswer: 'Tak sama! Objek legap (buku) hasilkan bayang jelas. Objek lut sinar (plastik jernih) tiada bayang!', trivia: 'Kaca tingkap rumah adalah lut sinar supaya cahaya penuh boleh masuk. 🪟' },
        { frontEmoji: '<img src="images/fox_permainan_bayang.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Permainan Bayang-bayang', frontQuestion: 'Boleh tak bayang-bayang bertukar saiz dan bentuk?', backEmoji: '<img src="images/bg_permainan_bayang.jpg" class="flashcard-bg-img">', backTitle: 'Boleh!', backAnswer: 'Saiz bayang berubah bergantung jarak lampu dengan objek. Bentuk pula ikut kedudukan objek.', trivia: 'Makin dekat objek dengan lampu, makin BESAR bayangnya! 📏' },
        { frontEmoji: '<img src="images/fox_wayang_kertas.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Mencipta Permainan Wayang Kertas', frontQuestion: 'Pernah tengok wayang kulit?', backEmoji: '<img src="images/bg_wayang_kertas.jpg" class="flashcard-bg-img">', backTitle: 'Guna Cahaya', backAnswer: 'Kita boleh cipta patung kertas sendiri. Suluh lampu dari belakang patung, dan bayangnya akan jatuh ke atas skrin putih di depan!', trivia: 'Wayang Kulit adalah permainan tradisional Melayu yang guna konsep bayang-bayang! 🪕' }
    ],
    'unit7': [
        { frontEmoji: '<img src="images/fox_kenali_komponen.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Kenali Komponen Elektrik', frontQuestion: 'Apa 3 komponen asas dalam litar elektrik?', backEmoji: '<img src="images/bg_kenali_komponen.jpg" class="flashcard-bg-img">', backTitle: 'Bateri, Suis, Mentol', backAnswer: 'Litar asas menggunakan Sel Kering (bateri), Suis, dan Mentol, disambung dengan wayar.', trivia: 'Bateri bersaiz AA yang kita selalu guna tu ialah contoh "Sel Kering". ⚡' },
        { frontEmoji: '<img src="images/fox_fungsi_komponen.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Fungsi Komponen Elektrik', frontQuestion: 'Apa tugas suis dalam litar elektrik?', backEmoji: '<img src="images/bg_fungsi_komponen.jpg" class="flashcard-bg-img">', backTitle: 'Menyambung Arus', backAnswer: 'Suis menyambung atau memutuskan arus. Mentol hasilkan cahaya. Sel Kering beri tenaga elektrik.', trivia: 'Tanpa sel kering, litar lengkap sekalipun takkan boleh menyalakan mentol. 🔋' },
        { frontEmoji: '<img src="images/fox_bina_litar.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Membina Litar Elektrik', frontQuestion: 'Bila mentol akan menyala?', backEmoji: '<img src="images/bg_bina_litar.jpg" class="flashcard-bg-img">', backTitle: 'Litar Lengkap', backAnswer: 'Mentol hanya akan menyala jika litar disambung lengkap dan suis DITUTUP (ON).', trivia: 'Perkataan "Tutup Suis" dalam sains bermaksud menyambungkan litar. Jangan keliru ya! 🔄', image: 'images/circuit.png?v=4' },
        { frontEmoji: '<img src="images/fox_mentol_tak_nyala.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Mengapakah Mentol Tidak Menyala?', frontQuestion: 'Saya dah pasang wayar, kenapa mentol masih tak nyala?', backEmoji: '<img src="images/bg_mentol_tak_nyala.jpg" class="flashcard-bg-img">', backTitle: 'Litar Tak Lengkap', backAnswer: 'Mungkin suis masih TERBUKA, sel kering habis tenaga, mentol rosak, atau pemasangan wayar salah.', trivia: 'Litar terbuka ibarat jambatan putus, arus elektrik tak boleh melintas! 🌉' },
        { frontEmoji: '<img src="images/fox_konduktor.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Konduktor dan Penebat', frontQuestion: 'Boleh ke wayar diganti dengan pemadam getah atau paku besi?', backEmoji: '<img src="images/bg_konduktor.jpg" class="flashcard-bg-img">', backTitle: 'Konduktor vs Penebat', backAnswer: 'Paku besi ialah KONDUKTOR (mengalirkan arus, mentol nyala). Pemadam ialah PENEBAT (menghalang arus, mentol padam).', trivia: 'Plastik membalut wayar elektrik di rumah awak ialah Penebat supaya awak tak terkena renjatan! ⚡🚫' }
    ],
    'unit8': [
        { frontEmoji: '<img src="images/fox_asing.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Kaedah Mengasingkan Campuran', frontQuestion: 'Klip kertas besi bercampur dalam tepung. Macam mana nak asingkan?', backEmoji: '<img src="images/bg_asing.jpg" class="flashcard-bg-img">', backTitle: 'Guna Magnet', backAnswer: 'Kita guna magnet. Kaedah lain: Menyisih, Mengayak, Menuras (guna penapis), dan Mengapung.', trivia: 'Mengayak sangat bagus untuk asingkan pasir kasar daripada gula halus! 🕳️' },
        { frontEmoji: '<img src="images/fox_boleh_larut.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Bahan Boleh Larut dan Tidak Boleh Larut', frontQuestion: 'Boleh ke batu kecil larut dalam air macam gula?', backEmoji: '<img src="images/bg_boleh_larut.jpg" class="flashcard-bg-img">', backTitle: 'Tak Boleh!', backAnswer: 'Gula dan garam boleh larut dalam air. Pasir dan batu TIDAK BOLEH larut.', trivia: 'Bahan larut akan "menghilang" bergabung dengan air, manakala bahan tidak larut akan mendap atau timbul. 🌊' },
        { frontEmoji: '<img src="images/fox_larut_cepat.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Bahan Larut Lebih Cepat', frontQuestion: 'Macam mana nak buat Milo cepat larut?', backEmoji: '<img src="images/bg_larut_cepat.jpg" class="flashcard-bg-img">', frontTitle: 'Air Panas & Kacau', backAnswer: 'Bahan larut LEBIH CEPAT jika: Menggunakan air panas, diaduk (kacau) laju, dan menggunakan saiz bahan yang kecil (halus).', trivia: 'Gula halus larut jauh lebih pantas berbanding ketulan gula batu besar! 🧊' }
    ],
    'unit9': [
        { frontEmoji: '<img src="images/fox_sumber_air.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Sumber Air Semula Jadi', frontQuestion: 'Air yang kita minum hari-hari, asalnya dari mana?', backEmoji: '<img src="images/bg_sumber_air.jpg" class="flashcard-bg-img">', backTitle: 'Hujan, Sungai, Laut', backAnswer: 'Sumber air semula jadi kita ialah hujan, sungai, tasik, laut, dan mata air.', trivia: 'Walaupun laut sangat besar, airnya masin dan tak boleh diminum terus! 🧂' },
        { frontEmoji: '<img src="images/fox_aliran_air.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Air Mengalir', frontQuestion: 'Adakah air di sungai duduk diam sahaja?', backEmoji: '<img src="images/bg_aliran_air.jpg" class="flashcard-bg-img">', backTitle: 'Air Bergerak', backAnswer: 'Tidak. Air sentiasa mengalir dari kawasan tinggi (gunung) menuju ke kawasan yang lebih rendah (laut).', trivia: 'Kawasan air mengalir yang jatuh dari tebing tinggi dipanggil Air Terjun! ⛰️' },
        { frontEmoji: '<img src="images/fox_aliran_semula_jadi.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Aliran Air Semula Jadi', frontQuestion: 'Ke manakah air sungai mengalir akhirnya?', backEmoji: '<img src="images/bg_aliran_semula_jadi.jpg" class="flashcard-bg-img">', backTitle: 'Menuju Laut', backAnswer: 'Air mengalir dari mata air di gunung, masuk ke sungai, dan akhirnya akan bermuara (berhenti) di lautan luas.', trivia: 'Perjalanan air ini sangat panjang dan menyokong kehidupan banyak haiwan darat! 🐘' },
        { frontEmoji: '<img src="images/fox_kitaran_air.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Kitaran Air Semula Jadi', frontQuestion: 'Macam mana hujan boleh terjadi?', backEmoji: '<img src="images/bg_kitaran_air.jpg" class="flashcard-bg-img">', backTitle: 'Wap Air Naik', backAnswer: 'Air sungai/laut menyejat jadi wap ➔ Naik ke langit jadi Awan ➔ Awan berat dan turunkan Hujan ➔ Balik ke sungai!', trivia: 'Kitaran air memastikan bekalan air di Bumi tak pernah habis! 🌍' },
        { frontEmoji: '<img src="images/fox_udara.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Udara', frontQuestion: 'Kita tak boleh nampak udara. Di mana ia wujud?', backEmoji: '<img src="images/bg_udara.jpg" class="flashcard-bg-img">', backTitle: 'Di Sekeliling Kita', backAnswer: 'Udara ada di mana-mana sahaja, termasuk dalam air dan tanah! Udara mengandungi pelbagai gas seperti oksigen.', trivia: 'Ikan di dalam laut pun bernafas menggunakan udara (oksigen) yang terlarut dalam air! 🐟' },
        { frontEmoji: '<img src="images/fox_angin.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Udara Bergerak', frontQuestion: 'Apa itu angin?', backEmoji: '<img src="images/bg_angin.jpg" class="flashcard-bg-img">', backTitle: 'Angin!', backAnswer: 'Udara yang bergerak dipanggil ANGIN. Angin membantu menerbangkan layang-layang dan mengeringkan baju.', trivia: 'Angin yang terlalu kuat dipanggil ribut dan boleh menumbangkan pokok! 🌲' },
        { frontEmoji: '<img src="images/fox_roket_angin.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Mencipta Roket Angin', frontQuestion: 'Boleh ke kita cipta mainan bergerak guna udara?', backEmoji: '<img src="images/bg_roket_angin.jpg" class="flashcard-bg-img">', backTitle: 'Boleh!', backAnswer: 'Kita boleh hasilkan roket kertas menggunakan belon. Udara yang keluar menolak belon meluncur laju ke depan.', trivia: 'Daya tolakan udara inilah yang digunakan oleh roket angkasa lepas sebenar! ✨' }
    ],
    'unit10': [
        { frontEmoji: '<img src="images/fox_binaan_pilihan.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Binaan Pilihan Saya', frontQuestion: 'Apa itu Set Binaan?', backEmoji: '<img src="images/bg_binaan_pilihan.jpg" class="flashcard-bg-img">', backTitle: 'Cantum Komponen', backAnswer: 'Set binaan (seperti Lego) mempunyai komponen berbeza bentuk untuk dicantumkan menjadi pelbagai model menarik.', trivia: 'Membina model melatih otak awak supaya lebih kreatif dan bijak menyelesaikan masalah! 🧠' },
        { frontEmoji: '<img src="images/fox_manual.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Mengenali Komponen dalam Manual Bergambar', frontQuestion: 'Kenapa bila beli mainan baru, ada satu buku kecil disertakan?', backEmoji: '<img src="images/bg_manual.jpg" class="flashcard-bg-img">', backTitle: 'Buku Manual', backAnswer: 'Manual menerangkan jenis komponen dan langkah-langkah memasang model secara teratur dan betul.', trivia: 'Jurutera sebenar pun merujuk "manual" atau pelan lantai sebelum membina rumah! 🏗️' },
        { frontEmoji: '<img src="images/fox_jurutera.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Jurutera Cilik', frontQuestion: 'Bagaimana cara nak pasang model robot tanpa salah langkah?', backEmoji: '<img src="images/bg_jurutera.jpg" class="flashcard-bg-img">', backTitle: 'Ikut Urutan', backAnswer: 'Awak mesti kenal pasti komponen dan ikut arahan bergambar dalam buku manual langkah demi langkah.', trivia: 'Kalau terlangkau satu langkah, robot awak mungkin tak boleh berdiri seimbang! 🤖' },
        { frontEmoji: '<img src="images/fox_kreatif.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Saya Kreatif', frontQuestion: 'Mesti ke sentiasa ikut manual?', backEmoji: '<img src="images/bg_kreatif.jpg" class="flashcard-bg-img">', backTitle: 'Tak Semestinya!', backAnswer: 'Lepas mahir, awak bebas berimaginasi! Awak boleh reka bentuk model unik sendiri seperti kereta terbang.', trivia: 'Perekacipta tersohor dunia bermula dengan selalu bermain mencantum barang baharu. 🌟' },
        { frontEmoji: '<img src="images/fox_simpan_binaan.png" style="width:100px;height:100px;object-fit:contain;">', frontTitle: 'Buka dan Simpan', frontQuestion: 'Dah siap main bina model, apa tanggungjawab kita?', backEmoji: '<img src="images/bg_simpan_binaan.jpg" class="flashcard-bg-img">', backTitle: 'Kemas Semula', backAnswer: 'Buka semula binaan mengikut urutan terbalik, asingkan ikut saiz/bentuk, dan simpan dalam bekas dengan kemas.', trivia: 'Kalau bersepah di lantai, komponen boleh hilang dan memijaknya akan sangat menyakitkan kaki! 😖' }
    ]
};
